type: segment_anything
name: lvm_sam_ssk_kvasir_vit_b_quant-r20230810
display_name: LVM-Med Kvasir SAM (ViT-Base Quant)
encoder_model_path: https://github.com/CVHub520/X-AnyLabeling/releases/download/v0.2.0/sam_model_best_large_ssl_kvasir.encoder.quant.onnx
decoder_model_path: https://github.com/CVHub520/X-AnyLabeling/releases/download/v0.2.0/sam_model_best_large_ssl_kvasir.decoder.quant.onnx
input_size: 1024
max_width: 1024
max_height: 682
