type: segment_anything
name: medsam_vit_b-r20230810
display_name: Medical SAM (ViT-Base)
encoder_model_path: https://github.com/CVHub520/X-AnyLabeling/releases/download/v0.2.0/medsam_vit_b.encoder.onnx
decoder_model_path: https://github.com/CVHub520/X-AnyLabeling/releases/download/v0.2.0/medsam_vit_b.decoder.onnx
input_size: 1024
max_width: 1024
max_height: 682
