type: segment_anything
name: segment_anything_vit_b_quant-r20230520
display_name: Segment Anything (ViT-B Quant)
encoder_model_path: https://github.com/CVHub520/X-AnyLabeling/releases/download/v0.1.0/segment_anything_vit_b_encoder_quant.onnx
decoder_model_path: https://github.com/CVHub520/X-AnyLabeling/releases/download/v0.1.0/segment_anything_vit_b_decoder_quant.onnx
input_size: 1024
max_width: 1024
max_height: 682
